[package]
name = "ratatui-blackjack-app"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.29.0"
inputbot = "0.6.0"
rand = "0.9.2"
ratatui = { version = "0.29.0", features = ["all-widgets"] }
rpassword = "7.4.0"
